### ISSUE TITLE
 text in cyrillic

### ISSUE THREAD

**Issue by ms301** [Steema/BI#7]
in **Data View** incorrect showing text in cyrillic
![kzix9zf](https://cloud.githubusercontent.com/assets/4525776/17275660/2458e190-5718-11e6-82e4-0e60576078b2.png)

**Comment by davidberneda** [comment]
The text conversion problem might happen at several parts (import, load, grid dataset or grid painting). Is it possible to email me a sample of the "category_description" data for me to reproduce?

**Comment by davidberneda** [comment]
I've been able to reproduce, doing:

  BIGrid1.Data:=TBIFileSource.FromFile('cyrillic.txt')

[cyrillic.txt](https://github.com/Steema/BI/files/394248/cyrillic.txt)

I'm investigating to fix it

**Comment by davidberneda** [comment]
I think the problem is fixed. TBIDataset (used by BIGrid etc) was not considering Unicode strings.
I'll commit a new "beta 15" as soon as possible, thanks for testing !

![teebi_unicode_widestring_bidataset](https://cloud.githubusercontent.com/assets/1636163/17301710/b509a548-5818-11e6-96d3-82f99e44ebbd.png)

**Comment by davidberneda** [comment]
beta 15 released, closing
